Update Remove PDF Password to Done
Modified routine to try pdftk first and then qpdf to remove password before failing with error message.
(Requires qpdf to be installed as well as pdftk)
Also, checks for Zenity to be installed.

diff --git a/Remove PDF Password to Done b/Remove PDF Password to Done
--- a/Remove PDF Password to Done
+++ b/Remove PDF Password to Done
@@ -1,9 +1,9 @@
 #! /bin/bash
 
 # AUTHOR:	(c) Jason Horan
-# NAME:	PDF Password Remove
+# NAME:	        qPDF Password Remove
 # DESCRIPTION:	A nice Nautilus script with a GUI to remove password from PDF files
-# REQUIRES:	pdftk, zenity
+# REQUIRES:	pdftk, qpdf, zenity
 # LICENSE:	GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
 # ACKNOWLEDGE:	Ricardo Ferreira Compress PDF https://launchpad.net/compress-pdf
 #		My colleagues who have assisted with the translations
@@ -11,91 +11,125 @@
 # Messages
 		# English (en-US)
 		error_nofiles="No file selected."
-		error_pdftk="PDF Remove Password requires the 'pdftk' package, which is not installed. Please install it and try again.  It is available in apt and as a snap."
+		error_qpdf="PDF Remove Password requires the 'qpdf' package, which is not installed. Please install it and try again.  It is available in apt and as a snap."
+                error_pdftk="PDF Remove Password requires the 'pdftk' package, which is not installed. Please install it and try again.  It is available in apt and as a snap."
 		error_nopdf="The selected file is not a valid PDF archive."
 		error_norun="The command could not run correctly."
 		job_done="has been successfully decoded."
+		error_zenity="Error - This script needs Zenity to run."
 
 case $LANG in
 
 	pl* )
 		# Polish (pl-PL) by Ania Lala
 		error_nofiles="Nie wybrano pliku."
-		error_pdftk="Ochrona hasłem PDF wymaga pakietu „pdftk”, który nie jest zainstalowany. Zainstaluj go i spróbuj ponownie. Jest dostępny w apt i na przystawkę."
+		error_qpdf="Ochrona hasłem PDF wymaga pakietu „qpdf”, który nie jest zainstalowany. Zainstaluj go i spróbuj ponownie. Jest dostępny w apt i na przystawkę."
+                error_pdftk="Ochrona hasłem PDF wymaga pakietu „pdftk”, który nie jest zainstalowany. Zainstaluj go i spróbuj ponownie. Jest dostępny w apt i na przystawkę."
 		error_nopdf="Wybrany plik nie jest prawidłowym archiwum PDF."
 		error_norun="Polecenie nie moglo zostać wykonane poprawnie."
-		job_done="został pomyślnie zdekodowany.";;
+		job_done="został pomyślnie zdekodowany."
+		error_zenity="Błąd - Do uruchomienia tego skryptu potrzebny jest Zenity.";;
 
 	es* )
 		# Spanish (es-AR) by Maury Guerrero
 		error_nofiles="No se detectó ningún archivo."
-		error_pdftk="El PDF protegido por contraseña requiere el paquete ‘pdftk’, el cual no está instalado. Instálelo e intente nuevamente. Está disponible en apt y como snap."
+		error_qpdf="El PDF protegido por contraseña requiere el paquete ‘qpdf’, el cual no está instalado. Instálelo e intente nuevamente. Está disponible en apt y como snap."
+                error_pdftk="El PDF protegido por contraseña requiere el paquete ‘pdftk’, el cual no está instalado. Instálelo e intente nuevamente. Está disponible en apt y como snap."
 		error_nopdf="El archivo seleccionado no es un archivo PDF válido."
 		error_norun="El comando no se pudo ejecutar correctamente."
-		job_done="ha sido decodificado exitosamente.";;
+		job_done="ha sido decodificado exitosamente."
+		error_zenity="Error: este script necesita Zenity para ejecutarse.";;
 
 	cs*)
 ﻿		# Czech (cz-CZ) by Hariraj Ji
 		error_nofiles="Žádný soubor není vybrán."
-		error_pdftk="Ochrana PDF heslem vyžaduje balíček „pdftk“, který není nainstalován. Nainstalujte si jej prosím a zkuste to znovu. Je k dispozici v apt a jako ‘snap’."
+		error_qpdf="Ochrana PDF heslem vyžaduje balíček „qpdf“, který není nainstalován. Nainstalujte si jej prosím a zkuste to znovu. Je k dispozici v apt a jako ‘snap’."
+                error_pdftk="Ochrana PDF heslem vyžaduje balíček „pdftk“, který není nainstalován. Nainstalujte si jej prosím a zkuste to znovu. Je k dispozici v apt a jako ‘snap’."
 		error_nopdf="Vybraný soubor není platným PDF archivem."
 		error_norun="Příkaz nebylo možno správně spustit."
-		job_done="byl úspěšně dekódován.";;
+		job_done="byl úspěšně dekódován."
+		error_zenity="Chyba - Tento skript vyžaduje ke spuštění Zenity.";;
 
 	fr*)
 ﻿		# French (fr-FR) by Georgios Diakidis
 		error_nofiles="Aucun fichier sélectionné."
-		error_pdftk="PDF Password Protect nécessite le package «pdftk», qui n'est pas installé. Veuillez l'installer et réessayer. Il est disponible en apt et en un clin d'œil."
+		error_qpdf="PDF Password Protect nécessite le package «qpdf», qui n'est pas installé. Veuillez l'installer et réessayer. Il est disponible en apt et en un clin d'œil."
+                error_pdftk="PDF Password Protect nécessite le package «pdftk», qui n'est pas installé. Veuillez l'installer et réessayer. Il est disponible en apt et en un clin d'œil."
 		error_nopdf="Le fichier sélectionné n'est pas une archive PDF valide."
 		error_norun="La commande n'a pas pu s'exécuter correctement."
-		job_done="a été décodé avec succès.";;
+		job_done="a été décodé avec succès."
+		error_zenity="Erreur - Ce script a besoin de Zenity pour s'exécuter.";;
 
 	el*)
 ﻿		# Greek (el-EL) by Georgios Diakidis
 		error_nofiles="Δεν έχει επιλεγεί κανένα αρχείο."
-		error_pdftk="Το PDF Password Protect απαιτεί το πακέτο «pdftk», το οποίο δεν είναι εγκατεστημένο. Παρακαλούμε, εγκαταστήστε το και δοκιμάστε ξανά. Είναι διαθέσιμο σε πακέτο apt και σε snap."
+		error_qpdf="Το PDF Password Protect απαιτεί το πακέτο «qpdf», το οποίο δεν είναι εγκατεστημένο. Παρακαλούμε, εγκαταστήστε το και δοκιμάστε ξανά. Είναι διαθέσιμο σε πακέτο apt και σε snap."
+                error_pdftk="Το PDF Password Protect απαιτεί το πακέτο «pdftk», το οποίο δεν είναι εγκατεστημένο. Παρακαλούμε, εγκαταστήστε το και δοκιμάστε ξανά. Είναι διαθέσιμο σε πακέτο apt και σε snap."
 		error_nopdf="Το επιλεγμένο αρχείο δεν είναι ένα έγκυρο αρχείο PDF."
 		error_norun="Δεν ήταν δυνατή η σωστή εκτέλεση της εντολής."
-		job_done="έχει αποκωδικοποιηθεί με επιτυχία.";;
+		job_done="έχει αποκωδικοποιηθεί με επιτυχία."
+		error_zenity="Σφάλμα - Αυτό το σενάριο χρειάζεται το Zenity για να εκτελεστεί.";;
 		
 	it*)
 ﻿		# Italian (it-IT) by Georgios Diakidis
 		error_nofiles="Nessun file selezionato."
-		error_pdftk="PDF Password Protect richiede il pacchetto "pdftk", che non è installato. Si prega di installarlo e di riprovare. È disponibile in apt e snap."
+		error_qpdf="PDF Password Protect richiede il pacchetto "qpdf", che non è installato. Si prega di installarlo e di riprovare. È disponibile in apt e snap."
+                error_pdftk="PDF Password Protect richiede il pacchetto "pdftk", che non è installato. Si prega di installarlo e di riprovare. È disponibile in apt e snap."
 		error_nopdf="Il file selezionato non è un archivio PDF valido."
 		error_norun="Il comando non può essere eseguito correttamente."
-		job_done="è stato decodificato con successo.";;
+		job_done="è stato decodificato con successo."
+		error_zenity="Errore: questo script necessita di Zenity per essere eseguito.";;
 
 	zh_CN*)
 		# Simplified Chinese  (zh_CN) by Paul Ayadoe
 		error_nofiles="没选择文件。"
-		error_pdftk="PDF Password Protect需要未安装的“ pdftk”软件包。 请安装它，然后重试。 它可以以apt的形式提供。"
+		error_qpdf="PDF Password Protect需要未安装的“ qpdf”软件包。 请安装它，然后重试。 它可以以apt的形式提供。"
+                error_pdftk="PDF Password Protect需要未安装的“ pdftk”软件包。 请安装它，然后重试。 它可以以apt的形式提供。"
 		error_nopdf="所选文件不是有效的PDF存档。"
 		error_norun="该命令无法正确运行。"
-		job_done="已成功解码。";;
+		job_done="已成功解码。"
+		error_zenity="错误 - 此脚本需要 Zenity 才能运行。";;
 
         ar*)
                 # Arabic (ar) by Khalid Siddig Abdalla Mohamed
 		error_nofiles=".لايوجد ملف محدد"
-		error_pdftk="ملف بدف محمي بكلمة سر ويحتاج لحزمة بدف تك, وهي غير متوفرة حاليا. الرجاء تنزيل الحزمة المذكورة أعلاه مرة أخرى. الحزمة متوفرة في نظام ابت  وكذلك نظام سناب."
+		error_qpdf="ملف بدف محمي بكلمة سر ويحتاج لحزمة بدف تك, وهي غير متوفرة حاليا. الرجاء تنزيل الحزمة المذكورة أعلاه مرة أخرى. الحزمة متوفرة في نظام ابت  وكذلك نظام سناب."
+                error_pdftk="ملف بدف محمي بكلمة سر ويحتاج لحزمة بدف تك, وهي غير متوفرة حاليا. الرجاء تنزيل الحزمة المذكورة أعلاه مرة أخرى. الحزمة متوفرة في نظام ابت  وكذلك نظام سناب."
 		error_nopdf="PDF الملف المحدد غير صالح في صيغة"
 		error_norun=".لا يمكن تشغيل الأمر بشكل صحيح"
-		job_done=".تم فك الشفرة بنجاح";;
+		job_done=".تم فك الشفرة بنجاح"
+		error_zenity="خطأ - يحتاج هذا البرنامج النصي إلى Zenity ليتم تشغيله.";;
 		
         ur*)
                 # Urdu (ur) by Asim Nayeem
 		error_nofiles=".کوئی فائل منتخب نہیں کی گئی"
-		error_pdftk="پی ڈی ایف پاس ورڈ پروٹیکٹ کیلئے 'pdftk' پیکیج کی ضرورت ہے ، جو انسٹال نہیں ہے۔ براہ کرم اسے انسٹال کریں اور دوبارہ کوشش کریں۔ یہ آپٹ میں اور ایک تصویر کے طور پر دستیاب ہے۔"
+		error_qpdf="پی ڈی ایف پاس ورڈ پروٹیکٹ کیلئے 'qpdf' پیکیج کی ضرورت ہے ، جو انسٹال نہیں ہے۔ براہ کرم اسے انسٹال کریں اور دوبارہ کوشش کریں۔ یہ آپٹ میں اور ایک تصویر کے طور پر دستیاب ہے۔"
+                error_pdftk="پی ڈی ایف پاس ورڈ پروٹیکٹ کیلئے 'pdftk' پیکیج کی ضرورت ہے ، جو انسٹال نہیں ہے۔ براہ کرم اسے انسٹال کریں اور دوبارہ کوشش کریں۔ یہ آپٹ میں اور ایک تصویر کے طور پر دستیاب ہے۔"
 		error_nopdf="اس نے منتخب کیا فائل درست PDF محفوظ شدہ دستاویزات نہیں ہے۔"
 		error_norun="کمانڈ صحیح طور پر نہیں چل سکی۔"
-		job_done="کامیابی کے ساتھ ضابطہ کشائی کی گئی ہے۔";;
+		job_done="کامیابی کے ساتھ ضابطہ کشائی کی گئی ہے۔"
+		error_zenity="خرابی - اس اسکرپٹ کو چلانے کے لیے زینٹی کی ضرورت ہے۔";;
 
 esac
 
-VERSION="1.0"
+VERSION="1.1"
 ZENITY=$(which zenity)
 
 pdf_file=$(basename "$1")
+
+# Check if Zenity is installed
+if ! ZENITY=$(which zenity)
+then
+	echo "$error_zenity"
+	exit 1
+fi
+
+# Check if qpdf is installed
+TK="/usr/bin/qpdf"
+if [ ! -x $TK ]; then
+        $ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_qpdf"
+        exit 0;
+fi
 
 # Check if pdftk is installed
 TK="/etc/alternatives/pdftk"
@@ -138,15 +172,14 @@ mkdir -p Done
 suggested_filename="$pdf_file"
 output_filename=Done/"$suggested_filename"
 
-if [ "$?" = 1 ] ; then
-        exit 0;
-fi
-
-# Remove password from PDF file
+# Remove password from PDF file (pdftk, if fails try qpdf)
 pdftk "$suggested_filename" input_pw $password output "$output_filename"
 if [ "$?" -ne 0 ] ; then
-        $ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_norun"
-        exit 0;
+        qpdf -password=$password -decrypt "$suggested_filename" "$output_filename"
+        if [ "$?" -ne 0 ] ; then
+                $ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_norun"
+                exit 0;
+        fi
 fi
-notify-send "PDF Remove Password" "$pdf_file $job_done"
 
+notify-send "PDF Remove Password" "$pdf_file $job_done"
